services:
  redis:
    container_name: laomaDJRedis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  mysql:
    container_name: laomaDJMySQL
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laomadj_customer
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  consul:
    container_name: laomaDJConsul
    image: consul
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0

